name: build

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - 'trunk'
    tags-ignore:
      - '**'

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: 19
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - run: ./gradlew build
